apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailer
  template:
    metadata:
      labels:
        app: mailer
    spec:
      containers:
        - name: mailer
          image: theocosmin/mailer
          resources:
            requests:
              memory: '250Mi'
              cpu: 200m
            limits:
              memory: '1000Mi'
              cpu: 1000m
          env:
            - name: HOST_URL
              value: mark.dev
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: mark
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: GMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mailer-secrets
                  key: GMAIL_PASSWORD
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            failureThreshold: 6
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /health
              port: 3000
            failureThreshold: 18
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: mailer-srv
  labels:
    app: mailer
spec:
  selector:
    app: mailer
  ports:
    - name: mailer
      protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: mailer-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mailer-depl
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
    scaleUp:
      stabilizationWindowSeconds: 0
