apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  name: auth
  namespace: default
spec:
  endpoints:
    - interval: 30s
      port: auth
  selector:
    matchLabels:
      app: auth
