apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  name: mailer
  namespace: default
spec:
  endpoints:
    - interval: 30s
      port: mailer
  selector:
    matchLabels:
      app: mailer
