apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  name: social
  namespace: default
spec:
  endpoints:
    - interval: 30s
      port: social
  selector:
    matchLabels:
      app: social
