apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  name: userprofile
  namespace: default
spec:
  endpoints:
    - interval: 30s
      port: userprofile
  selector:
    matchLabels:
      app: userprofile
