apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: theocosmin/auth
          resources:
            requests:
              memory: '250Mi'
              cpu: 200m
            limits:
              memory: '3072Mi'
              cpu: 1000m
          env:
            - name: HOST_URL
              value: theostanica.cloud.okteto.net
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: MONGO_URI
            - name: TWITTER_CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: TWITTER_CONSUMER_KEY
            - name: TWITTER_CONSUMER_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: TWITTER_CONSUMER_SECRET
            - name: FACEBOOK_APP_ID
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: FACEBOOK_APP_ID
            - name: FACEBOOK_APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: FACEBOOK_APP_SECRET
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: JWT_KEY
            - name: JWT_REFRESH_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: JWT_REFRESH_KEY
            - name: ACCESS_TOKEN_TTL
              value: '300'
            - name: REFRESH_TOKEN_TTL
              value: '86400'
            - name: REDIS_HOST
              value: auth-redis-srv
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: mark
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            failureThreshold: 6
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /health
              port: 3000
            failureThreshold: 18
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: auth-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-depl
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageValue: '950m'
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
    scaleUp:
      stabilizationWindowSeconds: 0
