apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social
  template:
    metadata:
      labels:
        app: social
    spec:
      containers:
        - name: social
          image: theocosmin/social
          resources:
            requests:
              memory: '250Mi'
              cpu: 200m
            limits:
              memory: '3072Mi'
              cpu: 1000m
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: social-secrets
                  key: MONGO_URI
            - name: TWITTER_CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  name: social-secrets
                  key: TWITTER_CONSUMER_KEY
            - name: TWITTER_CONSUMER_SECRET
              valueFrom:
                secretKeyRef:
                  name: social-secrets
                  key: TWITTER_CONSUMER_SECRET
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: social-secrets
                  key: JWT_KEY
            - name: JWT_REFRESH_KEY
              valueFrom:
                secretKeyRef:
                  name: social-secrets
                  key: JWT_REFRESH_KEY
            - name: RAPIDAPI_KEY
              valueFrom:
                secretKeyRef:
                  name: social-secrets
                  key: RAPIDAPI_KEY
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: mark
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            failureThreshold: 6
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /health
              port: 3000
            failureThreshold: 18
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: social-srv
spec:
  selector:
    app: social
  ports:
    - name: social
      protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: social-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: social-depl
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageValue: '950m'
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
    scaleUp:
      stabilizationWindowSeconds: 0
