#################################################################
##                                                             ##
##       NOTE: Secret keys must be base 64 encoded             ##
##       * JWT_KEY and JWT_REFRESH_KEY are the same            ##
##         for every microservice                              ##
##                                                             ##
#################################################################

apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
type: Opaque
data:
  MONGO_URI:
  TWITTER_CONSUMER_KEY:
  TWITTER_CONSUMER_SECRET:
  JWT_KEY:
  JWT_REFRESH_KEY:
  FACEBOOK_APP_ID:
  FACEBOOK_APP_SECRET:

---
apiVersion: v1
kind: Secret
metadata:
  name: mailer-secrets
type: Opaque
data:
  GMAIL_PASSWORD:

---
apiVersion: v1
kind: Secret
metadata:
  name: social-secrets
type: Opaque
data:
  MONGO_URI:
  TWITTER_CONSUMER_KEY:
  TWITTER_CONSUMER_SECRET:
  JWT_KEY:
  JWT_REFRESH_KEY:
  RAPIDAPI_KEY:

---
apiVersion: v1
kind: Secret
metadata:
  name: userprofile-secrets
type: Opaque
data:
  MONGO_URI:
  JWT_KEY:
  JWT_REFRESH_KEY:
  AWS_ACCESS_KEY:
  AWS_SECRET_KEY:
