apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
        - name: userprofile
          image: theocosmin/userprofile
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: userprofile-mongo-secret
                  key: MONGO_URI
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-access-key
                  key: AWS_ACCESS_KEY
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret-key
                  key: AWS_SECRET_KEY
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: mark
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: JWT_REFRESH_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-refresh-secret
                  key: JWT_REFRESH_KEY
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            failureThreshold: 3
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile-srv
spec:
  selector:
    app: userprofile
  ports:
    - name: userprofile
      protocol: TCP
      port: 3000
      targetPort: 3000
