export const UPDATE_VALUE = 'UPDATE_VALUE';

export const SET_ERRORS = 'SET_ERRORS';
export const RESET_ERRORS = 'RESET_ERRORS';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_REGISTER = 'USER_REGISTER';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_ERRORS = 'USER_ERRORS';
export const USER_RESEND_ACTIVATION = 'USER_RESEND_ACTIVATION';
export const USER_GET_INFO = 'USER_GET_INFO';
export const USER_SET_TOKENS = 'USER_SET_TOKENS';
export const USER_UPLOAD_PHOTO = 'USER_UPLOAD_PHOTO';

export const USER_SET_MESSAGES = 'USER_SET_MESSAGES';
export const USER_RESET_MESSAGES = 'USER_RESET_MESSAGES';

export const TWITTER_SET_PROFILE_INFO = 'TWITTER_SET_PROFILE_INFO';
export const TWITTER_RESET_PROFILE_INFO = 'TWITTER_RESET_PROFILE_INFO';
export const TWITTER_SET_HOME_TIMELINE_TWEETS =
  'TWITTER_SET_HOME_TIMELINE_TWEETS';
export const TWITTER_ADD_STREAM = 'TWITTER_ADD_STREAM';
export const TWITTER_UPDATE_STREAMS = 'TWITTER_UPDATE_STREAMS';
export const TWITTER_SET_STREAM_TWEETS = 'TWITTER_SET_STREAM_TWEETS';
export const TWITTER_SET_STREAM_LOADING_STATUS =
  'TWITTER_SET_STREAM_LOADING_STATUS';
export const TWITTER_REMOVE_STREAMBYID = 'TWITTER_REMOVE_STREAMBYID';
