export const UPDATE_VALUE = 'UPDATE_VALUE';

export const SET_ERRORS = 'SET_ERRORS';
export const RESET_ERRORS = 'RESET_ERRORS';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_REGISTER = 'USER_REGISTER';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_ERRORS = 'USER_ERRORS';
export const USER_RESEND_ACTIVATION = 'USER_RESEND_ACTIVATION';
export const USER_GET_INFO = 'USER_GET_INFO';
export const USER_SET_TOKENS = 'USER_SET_TOKENS';
