name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_ACCESS_TOKEN }}

      - uses: okteto/namespace@master

      - uses: okteto/apply@master
        with:
          manifest: infra/k8s-prod/auth-depl.yaml

      - uses: okteto/apply@master
        with:
          manifest: infra/k8s/auth-redis-depl.yaml

      - uses: okteto/apply@master
        with:
          manifest: infra/k8s-prod/mailer-depl.yaml

      - uses: okteto/apply@master
        with:
          manifest: infra/k8s/nats-depl.yaml

      - uses: okteto/apply@master
        with:
          manifest: infra/k8s/userprofile-depl.yaml

      - uses: okteto/apply@master
        with:
          manifest: infra/k8s-prod/ingress-srv.yaml

      - uses: okteto/apply@master
        with:
          manifest: infra/k8s/client-depl.yaml
