name: deploy-client

on:
  push:
    branches:
      - master
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client && docker build -t theocosmin/client .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push theocosmin/client
      - uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_ACCESS_TOKEN }}

      - uses: okteto/namespace@master

      - uses: okteto/apply@master
        with:
          manifest: infra/k8s/client-depl.yaml
