name: deploy-client

on:
  push:
    branches:
      - Feature/110-Okteto
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Image
        uses: actions/checkout@v2
        run: cd client && docker build -t theocosmin/client .

      - name: Login into Docker account
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image
        run: docker push theocosmin/client

      - name: Login into Okteto
        uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_ACCESS_TOKEN }}

      - name: Activate namespace
      - uses: okteto/namespace@master

      - name: Restart deployment
        uses: myrotvorets/kubectl-action@1.0.4
        env:
          KUBE_CONFIG_DATA: ${{ secrets.OKTETO_CONFIG_FILE }}
        with:
          args: rollout restart deployment client-depl
